// Generated by https://quicktype.io

export interface BookResponses {
  status: string;
  results: number;
  data: Data;
}

export interface Data {
  data: IBook[];
}

export interface IBook {
  _id: string;
  name: string;
  abbreviation: string;
  slug: string;
}
