// Generated by https://quicktype.io

export interface UserFavouriteSongsResponse {
  results: number;
  code: number;
  status: string;
  ok: boolean;
  data: FaveSong[];
}

export interface UserFavouriteSongResponse {
  code: number;
  status: string;
  ok: boolean;
  data: FaveSong;
}

export interface FaveSong {
  id: number;
  UserId: number;
  SongId: number;
}
